//applications
export const ADD_APPLICATION_ENTRY = "ADD_APPLICATION_ENTRY";
export const EDIT_APPLICATION_ENTRY = "EDIT_APPLICATION_ENTRY";
export const CLOSE_APPLICATION_ENTRY = "CLOSE_APPLICATION_ENTRY";
export const REMOVE_APPLICATION_ENTRY = "REMOVE_APPLICATION_ENTRY";
export const ADD_APPLICATION_STEP = "ADD_APPLICATION_STEP";
export const EDIT_APPLICATION_STEP = "EDIT_APPLICATION_STEP";
export const REMOVE_APPLICATION_STEP = "REMOVE_APPLICATION_STEP";
export const POPULATE_APPLICATIONS_STATE = "POPULATE_APPLICATIONS_STATE";
export const ACTIVE_STEP = "ACTIVE_STEP";
